// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/v1/mq/mq.proto

package mq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_mq_mq_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_api_v1_mq_mq_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{7, 0}
}

// Message represents a single message in the queue
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                       // Unique message ID
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                                                                                 // Topic the message belongs to
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                                                                             // Message payload
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Message metadata (headers, etc.)
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // Message creation timestamp
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`                                                                          // Message priority (higher is more important)
	Sequence      int64                  `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`                                                                          // Message sequence number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// PublishRequest is used to publish messages to the queue
type PublishRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                                 // The message to publish
	WaitForAck        bool                   `protobuf:"varint,2,opt,name=wait_for_ack,json=waitForAck,proto3" json:"wait_for_ack,omitempty"`                      // Whether to wait for acknowledgment
	AckTimeoutSeconds int32                  `protobuf:"varint,3,opt,name=ack_timeout_seconds,json=ackTimeoutSeconds,proto3" json:"ack_timeout_seconds,omitempty"` // Timeout for waiting for acknowledgment
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PublishRequest) GetWaitForAck() bool {
	if x != nil {
		return x.WaitForAck
	}
	return false
}

func (x *PublishRequest) GetAckTimeoutSeconds() int32 {
	if x != nil {
		return x.AckTimeoutSeconds
	}
	return 0
}

// PublishResponse is the response to a publish request
type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // The ID of the published message
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                     // Whether the publish was successful
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // Error message if publish failed
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Server timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{2}
}

func (x *PublishResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PublishResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SubscribeRequest is used to subscribe to messages from the queue
type SubscribeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Topic             string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                                                             // Topic to subscribe to
	ConsumerId        string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`                                                 // Unique consumer ID
	BatchSize         int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`                                                   // Maximum number of messages to receive in a batch
	MaxInFlight       int32                  `protobuf:"varint,4,opt,name=max_in_flight,json=maxInFlight,proto3" json:"max_in_flight,omitempty"`                                           // Maximum number of unacknowledged messages
	AckTimeoutSeconds int32                  `protobuf:"varint,5,opt,name=ack_timeout_seconds,json=ackTimeoutSeconds,proto3" json:"ack_timeout_seconds,omitempty"`                         // Timeout for message acknowledgment
	Filter            map[string]string      `protobuf:"bytes,6,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional filter criteria
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *SubscribeRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *SubscribeRequest) GetMaxInFlight() int32 {
	if x != nil {
		return x.MaxInFlight
	}
	return 0
}

func (x *SubscribeRequest) GetAckTimeoutSeconds() int32 {
	if x != nil {
		return x.AckTimeoutSeconds
	}
	return 0
}

func (x *SubscribeRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

// AcknowledgeRequest is used to acknowledge message processing
type AcknowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`    // ID of the message to acknowledge
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"` // ID of the consumer acknowledging the message
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                        // Whether processing was successful
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                             // Error message if processing failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{4}
}

func (x *AcknowledgeRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AcknowledgeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *AcknowledgeRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcknowledgeRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SubscribeResponse contains messages from the queue
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`    // Batch of messages
	Heartbeat     bool                   `protobuf:"varint,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"` // Whether this is a heartbeat message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SubscribeResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

// HealthCheckRequest is a health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"` // Service name to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// HealthCheckResponse is the health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=mq.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"` // Service status
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                             // Status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_v1_mq_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_mq_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_mq_mq_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_mq_mq_proto protoreflect.FileDescriptor

const file_api_v1_mq_mq_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/mq/mq.proto\x12\x05mq.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x128\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1c.mq.v1.Message.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x03R\bsequence\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x01\n" +
	"\x0ePublishRequest\x12(\n" +
	"\amessage\x18\x01 \x01(\v2\x0e.mq.v1.MessageR\amessage\x12 \n" +
	"\fwait_for_ack\x18\x02 \x01(\bR\n" +
	"waitForAck\x12.\n" +
	"\x13ack_timeout_seconds\x18\x03 \x01(\x05R\x11ackTimeoutSeconds\"\x9a\x01\n" +
	"\x0fPublishResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb4\x02\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12\"\n" +
	"\rmax_in_flight\x18\x04 \x01(\x05R\vmaxInFlight\x12.\n" +
	"\x13ack_timeout_seconds\x18\x05 \x01(\x05R\x11ackTimeoutSeconds\x12;\n" +
	"\x06filter\x18\x06 \x03(\v2#.mq.v1.SubscribeRequest.FilterEntryR\x06filter\x1a9\n" +
	"\vFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x12AcknowledgeRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"]\n" +
	"\x11SubscribeResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.mq.v1.MessageR\bmessages\x12\x1c\n" +
	"\theartbeat\x18\x02 \x01(\bR\theartbeat\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xad\x01\n" +
	"\x13HealthCheckResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.mq.v1.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\x9a\x01\n" +
	"\x10PublisherService\x12>\n" +
	"\aPublish\x12\x15.mq.v1.PublishRequest\x1a\x16.mq.v1.PublishResponse\"\x00(\x010\x01\x12F\n" +
	"\vHealthCheck\x12\x19.mq.v1.HealthCheckRequest\x1a\x1a.mq.v1.HealthCheckResponse\"\x002\xe7\x01\n" +
	"\x11SubscriberService\x12D\n" +
	"\tSubscribe\x12\x17.mq.v1.SubscribeRequest\x1a\x18.mq.v1.SubscribeResponse\"\x00(\x010\x01\x12D\n" +
	"\vAcknowledge\x12\x19.mq.v1.AcknowledgeRequest\x1a\x16.google.protobuf.Empty\"\x00(\x01\x12F\n" +
	"\vHealthCheck\x12\x19.mq.v1.HealthCheckRequest\x1a\x1a.mq.v1.HealthCheckResponse\"\x00B+Z)github.com/sreeram77/gpu-tel/api/v1/mq;mqb\x06proto3"

var (
	file_api_v1_mq_mq_proto_rawDescOnce sync.Once
	file_api_v1_mq_mq_proto_rawDescData []byte
)

func file_api_v1_mq_mq_proto_rawDescGZIP() []byte {
	file_api_v1_mq_mq_proto_rawDescOnce.Do(func() {
		file_api_v1_mq_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_mq_mq_proto_rawDesc), len(file_api_v1_mq_mq_proto_rawDesc)))
	})
	return file_api_v1_mq_mq_proto_rawDescData
}

var file_api_v1_mq_mq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_mq_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_mq_mq_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: mq.v1.HealthCheckResponse.ServingStatus
	(*Message)(nil),                        // 1: mq.v1.Message
	(*PublishRequest)(nil),                 // 2: mq.v1.PublishRequest
	(*PublishResponse)(nil),                // 3: mq.v1.PublishResponse
	(*SubscribeRequest)(nil),               // 4: mq.v1.SubscribeRequest
	(*AcknowledgeRequest)(nil),             // 5: mq.v1.AcknowledgeRequest
	(*SubscribeResponse)(nil),              // 6: mq.v1.SubscribeResponse
	(*HealthCheckRequest)(nil),             // 7: mq.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 8: mq.v1.HealthCheckResponse
	nil,                                    // 9: mq.v1.Message.MetadataEntry
	nil,                                    // 10: mq.v1.SubscribeRequest.FilterEntry
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 12: google.protobuf.Empty
}
var file_api_v1_mq_mq_proto_depIdxs = []int32{
	9,  // 0: mq.v1.Message.metadata:type_name -> mq.v1.Message.MetadataEntry
	11, // 1: mq.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: mq.v1.PublishRequest.message:type_name -> mq.v1.Message
	11, // 3: mq.v1.PublishResponse.timestamp:type_name -> google.protobuf.Timestamp
	10, // 4: mq.v1.SubscribeRequest.filter:type_name -> mq.v1.SubscribeRequest.FilterEntry
	1,  // 5: mq.v1.SubscribeResponse.messages:type_name -> mq.v1.Message
	0,  // 6: mq.v1.HealthCheckResponse.status:type_name -> mq.v1.HealthCheckResponse.ServingStatus
	2,  // 7: mq.v1.PublisherService.Publish:input_type -> mq.v1.PublishRequest
	7,  // 8: mq.v1.PublisherService.HealthCheck:input_type -> mq.v1.HealthCheckRequest
	4,  // 9: mq.v1.SubscriberService.Subscribe:input_type -> mq.v1.SubscribeRequest
	5,  // 10: mq.v1.SubscriberService.Acknowledge:input_type -> mq.v1.AcknowledgeRequest
	7,  // 11: mq.v1.SubscriberService.HealthCheck:input_type -> mq.v1.HealthCheckRequest
	3,  // 12: mq.v1.PublisherService.Publish:output_type -> mq.v1.PublishResponse
	8,  // 13: mq.v1.PublisherService.HealthCheck:output_type -> mq.v1.HealthCheckResponse
	6,  // 14: mq.v1.SubscriberService.Subscribe:output_type -> mq.v1.SubscribeResponse
	12, // 15: mq.v1.SubscriberService.Acknowledge:output_type -> google.protobuf.Empty
	8,  // 16: mq.v1.SubscriberService.HealthCheck:output_type -> mq.v1.HealthCheckResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_v1_mq_mq_proto_init() }
func file_api_v1_mq_mq_proto_init() {
	if File_api_v1_mq_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_mq_mq_proto_rawDesc), len(file_api_v1_mq_mq_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_v1_mq_mq_proto_goTypes,
		DependencyIndexes: file_api_v1_mq_mq_proto_depIdxs,
		EnumInfos:         file_api_v1_mq_mq_proto_enumTypes,
		MessageInfos:      file_api_v1_mq_mq_proto_msgTypes,
	}.Build()
	File_api_v1_mq_mq_proto = out.File
	file_api_v1_mq_mq_proto_goTypes = nil
	file_api_v1_mq_mq_proto_depIdxs = nil
}
